peer nodes joined channel

diff --git a/testNet/fabric-network/compose/docker-compose.yaml b/testNet/fabric-network/compose/docker-compose.yaml
--- a/testNet/fabric-network/compose/docker-compose.yaml
+++ b/testNet/fabric-network/compose/docker-compose.yaml
@@ -20,56 +20,55 @@ services:
 
   orderer.example.com:
     container_name: orderer.example.com
-    image: hyperledger/fabric-orderer:latest
+    image: hyperledger/fabric-orderer:3.0
     labels:
       service: hyperledger-fabric
     environment:
-      - FABRIC_CFG_PATH=/var/hyperledger/ordererConfig
+      - FABRIC_CFG_PATH=/etc/hyperledger/ordererConfig
       - FABRIC_LOGGING_SPEC=INFO
       - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
       - ORDERER_GENERAL_LISTENPORT=7050
       - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
-      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
+      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer/msp
       # enabled TLS
       - ORDERER_GENERAL_TLS_ENABLED=true
-      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
-      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
-      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
-      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
-      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
-      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
+      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/orderer/tls/server.key
+      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/orderer/tls/server.crt
+      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/orderer/tls/ca.crt]
+      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/orderer/tls/server.crt
+      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/orderer/tls/server.key
+      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/orderer/tls/ca.crt]
       - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
       - ORDERER_CHANNELPARTICIPATION_ENABLED=true
       - ORDERER_ADMIN_TLS_ENABLED=true
-      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
-      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
-      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
-      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
+      - ORDERER_ADMIN_TLS_CERTIFICATE=/etc/hyperledger/orderer/tls/server.crt
+      - ORDERER_ADMIN_TLS_PRIVATEKEY=/etc/hyperledger/orderer/tls/server.key
+      - ORDERER_ADMIN_TLS_ROOTCAS=[/etc/hyperledger/orderer/tls/ca.crt]
+      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/etc/hyperledger/orderer/tls/ca.crt]
       - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
       - ORDERER_OPERATIONS_LISTENADDRESS=orderer.example.com:9443
       - ORDERER_METRICS_PROVIDER=prometheus
-      - OSN_TLS_CA_ROOT_CERT=/var/hyperledger/orderer/tls/ca.crt
-      - ADMIN_TLS_SIGN_CERT=/var/hyperledger/users/Admin/tls/client.crt
-      - ADMIN_TLS_PRIVATE_KEY=/var/hyperledger/users/Admin/tls/client.key
-
+      - OSN_TLS_CA_ROOT_CERT=/etc/hyperledger/orderer/tls/ca.crt
+      #admin credentials
+      - ADMIN_TLS_SIGN_CERT=/etc/hyperledger/admin/tls/client.crt
+      - ADMIN_TLS_PRIVATE_KEY=/etc/hyperledger/admin/tls/client.key
     working_dir: /root
     command: 
       - /bin/sh
       - -c
       - |
-        orderer
-        osnadmin channel join --channelID Channel1 --config-block /etc/hyperledger/fabric/genesisblocks/genesis_block.pb -o orderer.example.com:7053 --ca-file $OSN_TLS_CA_ROOT_CERT --client-cert $ADMIN_TLS_SIGN_CERT --client-key $ADMIN_TLS_PRIVATE_KEY &&
+        orderer 
+        echo "CHECLOGTHISN" 
+        osnadmin channel join --channelID channel1 --config-block /etc/hyperledger/fabric/genesisblocks/genesis_block.pb -o orderer.example.com:7053 --ca-file $OSN_TLS_CA_ROOT_CERT --client-cert $ADMIN_TLS_SIGN_CERT --client-key $ADMIN_TLS_PRIVATE_KEY || echo "Command failed"
         echo "CHEKCING THIS WORKS" 
-      
-    
     volumes:
-      - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
-      - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
+      - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/:/etc/hyperledger/orderer/msp
+      - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/etc/hyperledger/orderer/tls
       - orderer.example.com:/var/hyperledger/production/orderer
-      - ../config/:/var/hyperledger/ordererConfig
+      - ../config/orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
       - ../channel-artifacts/:/etc/hyperledger/fabric/genesisblocks
-      - ../organizations/ordererOrganizations/example.com/users/Admin@example.com/tls/:/var/hyperledger/users/Admin/tls
-
+      - ../organizations/ordererOrganizations/example.com/users/Admin@example.com/:/etc/hyperledger/admin
+      - ../bin/:/usr/local/bin/
     ports:
       - 7050:7050
       - 7053:7053
@@ -79,7 +78,7 @@ services:
 
   peer0.org1.example.com:
     container_name: peer0.org1.example.com
-    image: hyperledger/fabric-peer:latest
+    image: hyperledger/fabric-peer:3.0
     labels:
       service: hyperledger-fabric
     environment:
@@ -88,9 +87,9 @@ services:
       #- FABRIC_LOGGING_SPEC=DEBUG
       - CORE_PEER_TLS_ENABLED=true
       - CORE_PEER_PROFILE_ENABLED=false
-      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
-      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
-      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
+      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/peers/peer0.org1.example.com/tls/server.crt
+      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/peers/peer0.org1.example.com/tls/server.key
+      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tlsca/tlsca.org1.example.com-cert.pem
       # Peer specific variables
       - CORE_PEER_ID=peer0.org1.example.com
       - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
@@ -100,18 +99,24 @@ services:
       - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
       - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
       - CORE_PEER_LOCALMSPID=Org1MSP
-      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
+      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/admin/msp
       - CORE_OPERATIONS_LISTENADDRESS=peer0.org1.example.com:9444
       - CORE_METRICS_PROVIDER=prometheus
       - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org1"}
       - CORE_CHAINCODE_EXECUTETIMEOUT=300s
+      - ADMIN_TLS_SIGN_CERT=/etc/hyperledger/admin/tls/client.crt
+      - ADMIN_TLS_PRIVATE_KEY=/etc/hyperledger/admin/tls/client.key
     volumes:
 
-      - ../organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com:/etc/hyperledger/fabric
+      - ../organizations/peerOrganizations/org1.example.com:/etc/hyperledger/fabric
       - peer0.org1.example.com:/var/hyperledger/production
       - ../config:/etc/hyperledger/peercfg
+      - ../channel-artifacts/:/etc/hyperledger/fabric/genesisblocks
+      - ../organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/:/etc/hyperledger/admin
     working_dir: /root
     command: peer node start
+    # peer channel fetch newest  channel1.block -c channel1 --orderer orderer.example.com:7050
+    #peer channel join -b /etc/hyperledger/fabric/genesisblocks/genesis_block.pb
     ports:
       - 7051:7051
       - 9444:9444
@@ -120,7 +125,7 @@ services:
 
   peer1.org1.example.com:
     container_name: peer1.org1.example.com
-    image: hyperledger/fabric-peer:latest
+    image: hyperledger/fabric-peer:3.0
     labels:
       service: hyperledger-fabric
     environment:
@@ -129,9 +134,9 @@ services:
       #- FABRIC_LOGGING_SPEC=DEBUG
       - CORE_PEER_TLS_ENABLED=true
       - CORE_PEER_PROFILE_ENABLED=false
-      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
-      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
-      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
+      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/peers/peer1.org1.example.com/tls/server.crt
+      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/peers/peer1.org1.example.com/tls/server.key
+      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tlsca/tlsca.org1.example.com-cert.pem
       # Peer specific variables
       - CORE_PEER_ID=peer1.org1.example.com
       - CORE_PEER_ADDRESS=peer1.org1.example.com:7060
@@ -141,15 +146,19 @@ services:
       - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:7060
       - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.example.com:7060
       - CORE_PEER_LOCALMSPID=Org1MSP
-      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
+      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/admin/msp
       - CORE_OPERATIONS_LISTENADDRESS=peer1.org1.example.com:9445
       - CORE_METRICS_PROVIDER=prometheus
       - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer1org1"}
       - CORE_CHAINCODE_EXECUTETIMEOUT=300s
+      - ADMIN_TLS_SIGN_CERT=/etc/hyperledger/admin/tls/client.crt
+      - ADMIN_TLS_PRIVATE_KEY=/etc/hyperledger/admin/tls/client.key
     volumes:
-      - ../organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com:/etc/hyperledger/fabric
+      - ../organizations/peerOrganizations/org1.example.com:/etc/hyperledger/fabric
       - peer1.org1.example.com:/var/hyperledger/production
       - ../config:/etc/hyperledger/peercfg
+      - ../channel-artifacts/:/etc/hyperledger/fabric/genesisblocks
+      - ../organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/:/etc/hyperledger/admin
     working_dir: /root
     command: peer node start
     ports:
@@ -160,7 +169,7 @@ services:
 
   peer2.org1.example.com:
     container_name: peer2.org1.example.com
-    image: hyperledger/fabric-peer:latest
+    image: hyperledger/fabric-peer:3.0
     labels:
       service: hyperledger-fabric
     environment:
@@ -169,9 +178,9 @@ services:
       #- FABRIC_LOGGING_SPEC=DEBUG
       - CORE_PEER_TLS_ENABLED=true
       - CORE_PEER_PROFILE_ENABLED=false
-      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
-      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
-      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
+      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/peers/peer2.org1.example.com/tls/server.crt
+      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/peers/peer2.org1.example.com/tls/server.key
+      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tlsca/tlsca.org1.example.com-cert.pem
       # Peer specific variables
       - CORE_PEER_ID=peer2.org1.example.com
       - CORE_PEER_ADDRESS=peer2.org1.example.com:7057
@@ -180,16 +189,20 @@ services:
       - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7058
       - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org1.example.com:7057
       - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.org1.example.com:7057
-      - CORE_PEER_LOCALMSPID=Org2MSP
-      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
+      - CORE_PEER_LOCALMSPID=Org1MSP
+      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/admin/msp
       - CORE_OPERATIONS_LISTENADDRESS=peer2.org1.example.com:9446
       - CORE_METRICS_PROVIDER=prometheus
       - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer2org1"}
       - CORE_CHAINCODE_EXECUTETIMEOUT=300s
+      - ADMIN_TLS_SIGN_CERT=/etc/hyperledger/admin/tls/client.crt
+      - ADMIN_TLS_PRIVATE_KEY=/etc/hyperledger/admin/tls/client.key
     volumes:
-      - ../organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com:/etc/hyperledger/fabric
+      - ../organizations/peerOrganizations/org1.example.com:/etc/hyperledger/fabric
       - peer2.org1.example.com:/var/hyperledger/production
       - ../config:/etc/hyperledger/peercfg
+      - ../channel-artifacts/:/etc/hyperledger/fabric/genesisblocks
+      - ../organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/:/etc/hyperledger/admin
     working_dir: /root
     command: peer node start
     ports:
